TILEDEF:str = '''
const tiledef_t &getTileDef(int i)
{
    return tileDefs[i];
}
'''

TILEDEF_STRUCT:str='''typedef struct
{
    uint8_t flags;
    uint8_t type;
    uint8_t score;
    int8_t health;
    uint8_t speed;
    uint8_t ai;
    bool hidden;
    const char * basename;
} tiledef_t;

const tiledef_t & getTileDef(int i);

'''

class TileDef:
    flag = '0x00'
    type_name = ''
    score = 0
    hp = 0
    speed = 0
    ai = 0
    hidden = False
    basename = ''
    tile_id = 0
    def_name = ''

    def to_string(self):
        item_def = f'''{{{self.flag}, TYPE_{self.type_name}, {self.score}, {self.hp}, {self.speed}, {self.ai}, {'true' if self.hidden else 'false'}, "{self.basename}"}}, '''
        return f'''     {item_def:70} // {self.tile_id:0>2x} {self.def_name}'''

def get_pair(line:str) -> list[str]:
    pair = []
    for e in line.split(' '):
        e = e.strip()
        if not e:
            continue
        if e[0] == '#':
            break
        pair.append(e)
    return pair

def main():
    defines = ['//////////////////////////////////////////////////',
               '// autogenerated',
               '#include <stdint.h>'
               '',
               '#pragma once',
               '',
               TILEDEF_STRUCT
               ]

    data = [
        '//////////////////////////////////////////////////',
        '// autogenerated',
        '',
        '#include "tilesdata.h"',
        '',
        'const tiledef_t tileDefs[] = {'
    ]

    tile_defs = []
    tiles = {}
    types = {}
    lines = []
    with open ('tiles.ini') as sfile:
        lines = sfile.read().split('\n')

    section = None
    line_num = 0
    i = 0
    for line in lines:
        line_num += 1
        line = line.strip().replace('\t', ' ')
        if not line:
            continue
        if line[0] == '#':
            continue

        if line[0] == '[':
            if section:
                defines.append('')
            section = line[1:-1]
            if section != 'tiledefs':
                defines.append(f'// {section}')
            i = 0
            continue

        if section:
            pair = get_pair(line)
            if not pair:
                continue
            def_name = pair[0].upper()
            def_name_raw = def_name
            prefix = def_name[0:len(section)]
            if prefix.upper() != section.upper():
                def_name = f'{section.upper()}_{def_name}'
            if section == 'type':
                types[def_name_raw] = 0
            c = line.split('#',1)
            name = c[1].strip() if len(c) > 1 else ''
            if section == 'tiledefs':
                if def_name_raw not in tiles:
                    print(f'missing tile {def_name_raw} in tiles on line {line_num}')
                    continue
                tile_id = tiles[def_name_raw]
                for j in range(1, len(pair)):
                    e = pair[j].split(':')
                    if (len(e) != 2):
                        print(f"missing pair value on line {line_num}")
                        continue
                    k,v= tuple(e)
                    if v[0] == '-':
                        value = v
                    else:
                        value = f'{k.upper()}_{v.upper()}'
                    setattr(tile_defs[tile_id], k, value)
                continue
            if len(pair) > 1 and len(pair[1]) == 2 :
                k = 2
                val = int(pair[1],16)
            else:
                k = 1
                val = i
            defines.append(f'#define {def_name:32} 0x{val:0>2x}' + (f' // {name}' if name else ''))
            if section == 'tiles':
                tiles[def_name] = val
                score = 0
                hp = 0
                if len(pair) > k + 1:
                    for j in range(k + 1, len(pair)):
                        if pair[j][0] == '+':
                           hp = int(pair[j][1:])
                        elif pair[j][0] == '-':
                           hp = int(pair[j])
                        elif pair[j][0] == '$':
                           score = int(pair[j][1:])
                        else:
                            print(f'unknown param `${pair[j]}` on line ${line}')
                if len(pair) > k:
                    type_name = pair[k]
                    if type_name not in types:
                        print(f'type_name {type_name} on line {line_num} not found')
                    else:
                        tile = TileDef()
                        tile.type_name = type_name
                        tile.score = score
                        tile.hp = hp
                        tile.basename = name
                        tile.tile_id = val
                        tile.def_name = def_name
                        tile_defs.append(tile)
                else:
                    print(f'warning: no type defined on line {line_num}')
            i += 1
        else:
            print(f'value no in section on line {line_num}')

    for line in tile_defs:
        data.append(line.to_string())

    with open('../../src/tilesdata.h', 'w') as tfile:
        tfile.write('\n'.join(defines))

    with open('../../src/tilesdata.cpp', 'w') as tfile:
        data.append('};')
        data.append(TILEDEF)
        tfile.write('\n'.join(data))

main()
