//////////////////////////////////////////////////
// autogenerated

#include "tilesdata.h"

const tiledef_t tileDefs[] = {
     {0x00, TYPE_BACKGROUND, 0, 0, 0, 0, false, "Blank"},                   // 00 TILES_BLANK
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "Brick"},                        // 01 TILES_BRICK
     {0x00, TYPE_PLAYER, 0, 0, 0, 0, false, "Player"},                      // 02 TILES_PLAYER
     {0x00, TYPE_PICKUP, 20, 0, 0, 0, false, "Light Bulb"},                 // 03 TILES_LIGHT_BULB
     {FLAG_EXTRA_LIFE, TYPE_PICKUP, 67, 10, 0, 0, false, "Orb"},            // 04 TILES_ORB
     {0x00, TYPE_PICKUP, 50, 0, 0, 0, false, "Chest"},                      // 05 TILES_CHEST
     {0x00, TYPE_DIAMOND, 10, 3, 0, 0, false, "Diamond"},                   // 06 TILES_DIAMOND
     {0x00, TYPE_PICKUP, 15, 8, 0, 0, false, "Neckless"},                   // 07 TILES_NECKLESS
     {0x00, TYPE_PICKUP, 20, 0, 0, 0, false, "Rope"},                       // 08 TILES_ROPE
     {0x00, TYPE_PICKUP, 66, 0, 0, 0, true, "Tnt"},                         // 09 TILES_TNT
     {0x00, TYPE_PICKUP, 5, 2, 0, 0, false, "Flower"},                      // 0a TILES_FLOWER
     {0x00, TYPE_PICKUP, 5, 0, 0, 0, false, "Bottle of Oxygen"},            // 0b TILES_OXYGEN_BOTTLE
     {FLAG_EXTRA_SPEED, TYPE_PICKUP, 99, 20, 0, 0, false, "TriForce"},      // 0c TILES_TRIFORCE
     {FLAG_GODMODE, TYPE_PICKUP, 37, 0, 0, 0, false, "Shield"},             // 0d TILES_SHIELD
     {0x00, TYPE_LADDER, 0, 0, 0, 0, false, "Ladder"},                      // 0e TILES_LADDER
     {0x00, TYPE_AUTO_ROPE, 0, 0, 0, 0, true, "LEFT Rope <- Pulley"},       // 0f TILES_LEFT_ROPE_PULLEY
     {0x00, TYPE_PULLEY, 0, 0, 0, 0, false, "LEFT Pulley (no rope)"},       // 10 TILES_LEFT_PULLEY
     {0x00, TYPE_AUTO_ROPE, 0, 0, 0, 0, true, "LEFT Rope    Pulley"},       // 11 TILES_LEFT_ROPE
     {0x00, TYPE_PULLEY, 0, 0, 0, 0, false, "RIGHT Pulley (no rope)"},      // 12 TILES_RIGHT_PULLEY
     {0x00, TYPE_AUTO_ROPE, 0, 0, 0, 0, true, "RIGHT Pulley -> Rope"},      // 13 TILES_RIGHT_PULLEY_ROPE
     {0x00, TYPE_AUTO_ROPE, 0, 0, 0, 0, true, "RIGHT Pulley    Rope"},      // 14 TILES_RIGHT_ROPE
     {0x00, TYPE_SWITCH, 0, 0, 0, 0, false, "ELectric SWitch UP"},          // 15 TILES_SWITCH_UP
     {0x00, TYPE_SWITCH, 0, 0, 0, 0, false, "ELectric SWitch DN"},          // 16 TILES_SWITCH_DOWN
     {0x00, TYPE_SOCKET, 0, 0, 0, 0, false, "Socket ON"},                   // 17 TILES_SOCKET_ON
     {0x00, TYPE_SOCKET, 0, 0, 0, 0, false, "Light Bulb in Socket ON"},     // 18 TILES_LIGHTBULB_SOCKET_ON
     {0x00, TYPE_SOCKET, 0, 0, 0, 0, false, "Socket OFF"},                  // 19 TILES_SOCKET_OFF
     {0x00, TYPE_SOCKET, 0, 0, 0, 0, false, "Light Bulb in Socket OFF"},    // 1a TILES_LIGHTBULB_SOCKET_OFF
     {0x00, TYPE_PICKUP, 50, 0, 0, 0, false, "Magic Box"},                  // 1b TILES_MAGIC_BOX
     {0x00, TYPE_PULLEY, 0, 0, 0, 0, false, "Left Pulley with rope"},       // 1c TILES_LEFT_PULLEY_WITH_ROPE
     {0x00, TYPE_PULLEY, 0, 0, 0, 0, false, "Right Pulley with rope"},      // 1d TILES_RIGHT_PULLEY_WITH_ROPE
     {0x00, TYPE_KEY, 25, 0, 0, 0, false, "HeartKey"},                      // 1e TILES_HEARTKEY
     {0x00, TYPE_DOOR, 0, 0, 0, 0, false, "HeartDoor"},                     // 1f TILES_HEARTDOOR
     {0x00, TYPE_KEY, 25, 0, 0, 0, false, "WaterKey"},                      // 20 TILES_WATERKEY
     {0x00, TYPE_DOOR, 0, 0, 0, 0, false, "WaterDoor"},                     // 21 TILES_WATERDOOR
     {0x00, TYPE_KEY, 25, 0, 0, 0, false, "SKey"},                          // 22 TILES_SKEY
     {0x00, TYPE_DOOR, 0, 0, 0, 0, false, "SDoor"},                         // 23 TILES_SDOOR
     {0x00, TYPE_KEY, 25, 0, 0, 0, false, "BKey"},                          // 24 TILES_BKEY
     {0x00, TYPE_DOOR, 0, 0, 0, 0, false, "BDoor"},                         // 25 TILES_BDOOR
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "GreenWall"},                    // 26 TILES_GREENWALL
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "Pattern"},                      // 27 TILES_PATTERN
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "Rockwall93"},                   // 28 TILES_ROCKWALL93
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "Rockwall"},                     // 29 TILES_ROCKWALL
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "Rockwall UP"},                  // 2a TILES_ROCKWALL_UP
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "Rockwall DN"},                  // 2b TILES_ROCKWALL_DN
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "NewPattern"},                   // 2c TILES_NEWPATTERN
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "BluePattern"},                  // 2d TILES_BLUEPATTERN
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "Pine Tree"},                    // 2e TILES_PINE_TREE
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "Statue"},                       // 2f TILES_STATUE
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "Rock"},                         // 30 TILES_ROCK
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "Rock #2"},                      // 31 TILES_ROCK_2
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "Rock #3"},                      // 32 TILES_ROCK_3
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "Rock & NewPlant"},              // 33 TILES_ROCK_NEWPLANT
     {0x00, TYPE_BACKGROUND, 0, 0, 0, 0, false, "New Plant"},               // 34 TILES_NEW_PLANT
     {0x00, TYPE_TRAP, 0, 0, 0, 0, false, "Breakable ROOT"},                // 35 TILES_BREAKABLE_ROOT
     {0x00, TYPE_ROOT, 0, 0, 0, 0, false, "ROOT"},                          // 36 TILES_ROOT
     {0x00, TYPE_BRIDGE, 0, 0, 0, 0, false, "BRIDGE & ROOT"},               // 37 TILES_BRIDGE_ROOT
     {0x00, TYPE_BRIDGE, 0, 0, 0, 0, false, "BRIDGE #0"},                   // 38 TILES_BRIDGE_0
     {0x00, TYPE_BRIDGE, 0, 0, 0, 0, false, "BRIDGE #1"},                   // 39 TILES_BRIDGE_1
     {0x00, TYPE_BRIDGE, 0, 0, 0, 0, false, "BRIDGE #2"},                   // 3a TILES_BRIDGE_2
     {0x00, TYPE_BRIDGE, 0, 0, 0, 0, false, "BRIDGE #3"},                   // 3b TILES_BRIDGE_3
     {0x00, TYPE_BRIDGE, 0, 0, 0, 0, false, "BRIDGE #4"},                   // 3c TILES_BRIDGE_4
     {0x00, TYPE_BRIDGE, 0, 0, 0, 0, false, "BRIDGE #5"},                   // 3d TILES_BRIDGE_5
     {0x00, TYPE_BRIDGE, 0, 0, 0, 0, false, "BRIDGE #6"},                   // 3e TILES_BRIDGE_6
     {0x00, TYPE_BRIDGE, 0, 0, 0, 0, false, "BRIDGE #7"},                   // 3f TILES_BRIDGE_7
     {0x00, TYPE_BRIDGE, 0, 0, 0, 0, false, "BRIDGE #8"},                   // 40 TILES_BRIDGE_8
     {0x00, TYPE_BRIDGE, 0, 0, 0, 0, false, "BRIDGE #9"},                   // 41 TILES_BRIDGE_9
     {0x00, TYPE_BRIDGE, 0, 0, 0, 0, false, "BRIDGE #10"},                  // 42 TILES_BRIDGE_10
     {0x00, TYPE_BRIDGE, 0, 0, 0, 0, false, "BRIDGE #11"},                  // 43 TILES_BRIDGE_11
     {0x00, TYPE_WALLS, 0, 0, 0, 0, false, "Force Field"},                  // 44 TILES_FORCE_FIELD
     {0x00, TYPE_STOP, 0, 0, 0, 0, false, "Stop"},                          // 45 TILES_STOP
     {0x00, TYPE_TRAP, 0, -12, 0, 0, false, "Energy Drain Trap"},           // 46 TILES_ENERGY_DRAIN_TRAP
     {0x00, TYPE_TRAP, 0, 0, 0, 0, false, "Freeze Trap"},                   // 47 TILES_FREEZE_TRAP
     {0x00, TYPE_TRANS_SOURCE, 0, 0, 0, 0, false, "Transporter"},           // 48 TILES_TRANSPORTER
     {0x00, TYPE_TRANS_DEST, 0, 0, 0, 0, false, "Transporter's destination"},  // 49 TILES_TRANSPORTER_DEST
     {0x00, TYPE_VAMPLANT, 0, -1, SPEED_NORMAL, AI_CLASSIC, false, "Vampire Plant"},  // 4a TILES_VAMPLANT
     {0x00, TYPE_DRONE, 0, -2, SPEED_SLOW, AI_CLASSIC, false, "Fish"},      // 4b TILES_FISH
     {0x00, TYPE_MONSTER, 0, -5, SPEED_NORMAL, AI_CLASSIC, false, "Change Link"},  // 4c TILES_CHANGE_LINK
     {0x00, TYPE_UNUSED, 0, 0, 0, 0, true, "Boby of the worm"},             // 4d TILES_BOBY_OF_THE_WORM
     {0x00, TYPE_PLATFORM, 0, 0, SPEED_VERYSLOW, 0, false, "Magic Platform UP/DN"},  // 4e TILES_PLATFORM_UP_DN
     {0x00, TYPE_PLATFORM, 0, 0, SPEED_VERYSLOW, 0, false, "Magic Platform LF/RG"},  // 4f TILES_PLATFORM_LF_RG
     {0x00, TYPE_MONSTER, 0, -2, SPEED_SLOW, AI_CLASSIC, false, "Dummy"},   // 50 TILES_DUMMY
     {0x00, TYPE_MONSTER, 0, 0, 0, 0, false, "Dummy on bridge"},            // 51 TILES_DUMMY_ON_BRIDGE
     {0x00, TYPE_MONSTER, 0, 0, 0, 0, false, "Dummy on ladder"},            // 52 TILES_DUMMY_ON_LADDER
     {0x00, TYPE_MONSTER, 0, -3, SPEED_SLOW, AI_CLASSIC, false, "Gobblin"},  // 53 TILES_GOBBLIN
     {0x00, TYPE_MONSTER, 0, 0, 0, 0, false, "Gobblin on bridge"},          // 54 TILES_GOBBLIN_ON_BRIDGE
     {0x00, TYPE_MONSTER, 0, 0, 0, 0, false, "Gobblin on ladder"},          // 55 TILES_GOBBLIN_ON_LADDER
     {0x00, TYPE_MONSTER, 0, -3, SPEED_NORMAL, AI_CLASSIC, false, "Teddy"},  // 56 TILES_TEDDY
     {0x00, TYPE_MONSTER, 0, 0, 0, 0, false, "Teddy on bridge"},            // 57 TILES_TEDDY_ON_BRIDGE
     {0x00, TYPE_MONSTER, 0, 0, 0, 0, false, "Teddy on ladder"},            // 58 TILES_TEDDY_ON_LADDER
     {0x00, TYPE_MONSTER, 0, -4, SPEED_NORMAL, AI_CLASSIC, false, "Octopus"},  // 59 TILES_OCTOPUS
     {0x00, TYPE_MONSTER, 0, 0, 0, 0, false, "Octopus on bridge"},          // 5a TILES_OCTOPUS_ON_BRIDGE
     {0x00, TYPE_MONSTER, 0, 0, 0, 0, false, "Octopus on ladder"},          // 5b TILES_OCTOPUS_ON_LADDER
};

const tiledef_t &getTileDef(int i)
{
    return tileDefs[i];
}
